/**
 * Find and merge duplicate catalog products (same barcode, multiple documents).
 *
 * WHY THIS MATTERS
 *
 * Every lookup path resolves a barcode with `.where('barcode','==',x).limit(1)`:
 *
 *   productLookup.lookupProduct     — the device scan path
 *   inventory.updateProductConfig   — spec and pricing edits
 *   inventory.createReading         — attaching product metadata to a reading
 *   bottle.upsertByBarcode          — the mobile add/edit product form
 *
 * Firestore gives no ordering guarantee on `limit(1)` without an `orderBy`, so
 * with duplicates present *an arbitrary document wins, and not necessarily the
 * same one each time*. The user-visible symptoms are subtle and maddening:
 *
 *   - Set a pour price in the app; scans keep using the old one.
 *   - Measure a bottle's weights; the dashboard still says specs are missing.
 *   - Two readings for "the same" product land on different product_ids, so
 *     consumption is split across what looks like one item.
 *
 * Usage:
 *   npm run build
 *   node lib/scripts/dedupe_catalog.js                 # audit only (default)
 *   node lib/scripts/dedupe_catalog.js --merge         # merge duplicates
 *   node lib/scripts/dedupe_catalog.js --merge --yes   # skip the confirmation
 *
 * Merging keeps one canonical document per barcode, repoints every reference to
 * it, and deletes the rest. It is destructive — take a Firestore export first.
 */

import { db } from '../firebase';

const COLLECTION = 'bottles';

/** Collections that reference a bottle document, and the field they use. */
const REFERENCES: { collection: string; field: string }[] = [
  { collection: 'inventory_readings', field: 'product_id' },
  { collection: 'inventory_events', field: 'product_id' },
  { collection: 'consumption_reports', field: 'items' }, // nested; reported only
  { collection: 'bottle-stats', field: 'bottle' },
  { collection: 'demo_inventory', field: 'product_id' },
];

interface Doc {
  id: string;
  data: any;
}

/**
 * Score a document so the richest survives a merge.
 *
 * Measured specs outrank estimated ones by a wide margin: a real measurement is
 * expensive to reproduce (someone stood at a scale with a bottle), while an
 * estimate can always be regenerated by the backfill.
 */
function score(d: Doc): number {
  const b = d.data;
  let s = 0;
  if (b.specs_estimated === false && Number(b.bottle_empty_weight_g) > 0) s += 1000;
  if (Number(b.bottle_full_weight_g) > 0) s += 50;
  if (Number(b.bottle_empty_weight_g) > 0) s += 50;
  if (Number(b.bottle_volume_ml) > 0) s += 50;
  if (Number(b.cost_per_bottle) > 0) s += 30;
  if (Number(b.pour_price) > 0) s += 30;
  if (Number(b.pour_volume_ml) > 0) s += 20;
  if (Number(b.par_level) > 0) s += 10;
  if (b.image_url) s += 15;
  if (b.category) s += 10;
  if (b.description) s += 5;
  if (b.brand) s += 5;
  if (b.source === 'manual') s += 40;  // hand-entered beats bulk-imported
  return s;
}

/** Fill gaps in the winner from the losers — never overwrite a set value. */
function mergeInto(winner: any, losers: any[]): any {
  const merged = { ...winner };
  const fields = [
    'name', 'brand', 'description', 'category', 'image_url', 'quantity', 'weight',
    'country_of_origin', 'ingredients', 'nutrition_per_100',
    'bottle_full_weight_g', 'bottle_empty_weight_g', 'bottle_volume_ml',
    'cost_per_bottle', 'pour_price', 'pour_volume_ml', 'par_level',
  ];
  for (const f of fields) {
    const empty = merged[f] === undefined || merged[f] === null || merged[f] === '';
    if (!empty) continue;
    for (const l of losers) {
      if (l[f] !== undefined && l[f] !== null && l[f] !== '') {
        merged[f] = l[f];
        break;
      }
    }
  }
  return merged;
}

/** Normalise a product name for comparison: case, punctuation, spacing. */
function normaliseName(name: any): string {
  return String(name || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

/**
 * Report the *other* kind of duplication: one physical bottle reachable under
 * more than one barcode.
 *
 * The source spreadsheet carries two distinct codes per item — a PLCB SCC and a
 * manufacturer SCC — with zero overlap between the two columns. If both were
 * imported, the catalog holds two documents for the same bottle, each with a
 * unique barcode. A barcode-level audit sees nothing wrong, because nothing is
 * wrong at that level.
 *
 * Registering both codes is *correct* for scanning: whichever code the scanner
 * reads should resolve. The problem is that the two documents are independent,
 * so pricing and measurements applied to one are invisible from the other:
 *
 *   - set a pour price under one code, scan the other, get no price
 *   - measure the bottle under one code, the other still reports missing specs
 *   - consumption splits across two product_ids for one physical bottle
 *
 * The fix is therefore *not* deletion — you would lose a working barcode.
 * This reports the scale of it so the right remedy can be chosen.
 */
async function auditProductLevelDuplicates(snapshot: any) {
  console.log('─── Same product under multiple barcodes ─');

  const byProduct = new Map<string, { id: string; data: any }[]>();
  snapshot.docs.forEach((doc: any) => {
    const d = doc.data();
    const key = `${normaliseName(d.name)}|${d.bottle_volume_ml ?? d.quantity ?? ''}`;
    if (!normaliseName(d.name)) return;
    if (!byProduct.has(key)) byProduct.set(key, []);
    byProduct.get(key)!.push({ id: doc.id, data: d });
  });

  const multi = Array.from(byProduct.entries()).filter(([, l]) => l.length > 1);
  const redundant = multi.reduce((s, [, l]) => s + l.length - 1, 0);

  console.log(`  distinct products (name + volume) : ${byProduct.size}`);
  console.log(`  products with >1 barcode          : ${multi.length}`);
  console.log(`  extra documents they account for  : ${redundant}`);

  if (!multi.length) {
    console.log('\n  Catalog is clean at the product level too. Nothing to do.');
    return;
  }

  // Only disagreements cause user-visible problems.
  //
  // Report *which* field disagrees and print that field's values. An earlier
  // version flagged on cost but printed only price and measurement state, so
  // the examples looked identical to each other and the output read like a
  // false positive.
  const CHECKED: { field: string; label: string; read: (d: any) => string }[] = [
    { field: 'pour_price', label: 'price', read: d => d.pour_price ?? '-' },
    { field: 'cost_per_bottle', label: 'cost', read: d => d.cost_per_bottle ?? '-' },
    { field: 'bottle_volume_ml', label: 'volume', read: d => d.bottle_volume_ml ?? '-' },
    { field: 'bottle_empty_weight_g', label: 'empty', read: d => d.bottle_empty_weight_g ?? '-' },
    { field: 'measured', label: 'measured', read: d => String(d.specs_estimated === false) },
  ];

  let diverged = 0;
  const examples: string[] = [];
  const fieldTally: Record<string, number> = {};

  for (const [, list] of multi) {
    const differing = CHECKED.filter(c => new Set(list.map(d => String(c.read(d.data)))).size > 1);
    if (!differing.length) continue;

    diverged++;
    differing.forEach(c => { fieldTally[c.label] = (fieldTally[c.label] || 0) + 1; });

    if (examples.length < 10) {
      const shown = differing.map(c => c.label).join(', ');
      examples.push(
        `    ${list[0].data.name}\n      differs on: ${shown}\n` +
        list.map(d =>
          `        ${d.data.barcode}  ` +
          differing.map(c => `${c.label}=${c.read(d.data)}`).join('  ')
        ).join('\n')
      );
    }
  }

  console.log(`  of those, with differing data     : ${diverged}`);
  if (Object.keys(fieldTally).length) {
    console.log(`  fields that differ                : `
      + Object.entries(fieldTally).map(([f, n]) => `${f} (${n})`).join(', '));
  }
  if (examples.length) {
    console.log('\n  Details:');
    examples.forEach(e => console.log(e));
    if (diverged > examples.length) console.log(`    … and ${diverged - examples.length} more`);
  }

  const pct = ((multi.length / byProduct.size) * 100).toFixed(2);
  console.log('\n  What this means');
  console.log('  ---------------');
  console.log(`  ${multi.length} of ${byProduct.size} products (${pct}%) share a name and volume`);
  console.log('  with another entry under a different barcode.');
  console.log('');
  if (multi.length < byProduct.size * 0.01) {
    console.log('  That is a small enough fraction to be normal catalog noise: genuine');
    console.log('  UPC/EAN variants of one bottle, or different releases that happen to');
    console.log('  share a label. It does not indicate a broken import.');
    console.log('');
    console.log('  Worth a manual look only where the fields above actually differ —');
    console.log('  a bottle scanned under one code will not see a price set under the');
    console.log('  other. At this scale, fix those by hand in the dashboard.');
  } else {
    console.log('  That is a large enough fraction to suggest the same catalog was');
    console.log('  imported under two barcode schemes. If so, an alias — one canonical');
    console.log('  record, the other pointing at it — is better than deleting either,');
    console.log('  since both codes may legitimately scan.');
  }
  console.log('');
  console.log('  --merge does NOT act on these. It only collapses documents that share');
  console.log('  an identical barcode, and there are none.');
}

async function main() {
  const merge = process.argv.includes('--merge');
  const skipConfirm = process.argv.includes('--yes');

  console.log(merge ? 'MERGE MODE — this will delete documents.\n' : 'AUDIT ONLY — no writes.\n');

  const projectId = await (db as any)._getProjectId?.().catch(() => null)
    ?? process.env.GOOGLE_CLOUD_PROJECT ?? '(unknown)';
  console.log(`Target project: ${projectId}`);
  const expected = process.env.SMARTBAR_PROJECT_ID;
  if (expected && projectId !== expected && projectId !== '(unknown)') {
    console.error(`\nRefusing: SMARTBAR_PROJECT_ID is "${expected}" but credentials resolve to "${projectId}".`);
    process.exit(1);
  }
  console.log('');

  const snapshot = await db.collection(COLLECTION).get();
  console.log(`Scanning ${snapshot.size} catalog documents…\n`);

  const byBarcode = new Map<string, Doc[]>();
  let noBarcode = 0;
  snapshot.docs.forEach(doc => {
    const data = doc.data();
    const barcode = String(data.barcode || '').trim();
    if (!barcode) { noBarcode++; return; }
    if (!byBarcode.has(barcode)) byBarcode.set(barcode, []);
    byBarcode.get(barcode)!.push({ id: doc.id, data });
  });

  const dupes = Array.from(byBarcode.entries()).filter(([, list]) => list.length > 1);
  const extra = dupes.reduce((s, [, l]) => s + l.length - 1, 0);

  console.log('─── Audit ────────────────────────────────');
  console.log(`  documents                : ${snapshot.size}`);
  console.log(`  without a barcode        : ${noBarcode}`);
  console.log(`  distinct barcodes        : ${byBarcode.size}`);
  console.log(`  barcodes with duplicates : ${dupes.length}`);
  console.log(`  redundant documents      : ${extra}`);

  if (!dupes.length) {
    console.log('\nNo duplicate barcodes. Every barcode resolves to exactly one document.\n');
    await auditProductLevelDuplicates(snapshot);
    return;
  }

  // How much do duplicates actually disagree? Identical copies are safe to
  // collapse; conflicting ones deserve a human look.
  let conflicting = 0;
  const conflicts: string[] = [];
  for (const [barcode, list] of dupes) {
    const names = new Set(list.map(d => String(d.data.name || '')));
    const costs = new Set(list.map(d => String(d.data.cost_per_bottle ?? '')));
    const prices = new Set(list.map(d => String(d.data.pour_price ?? '')));
    if (names.size > 1 || costs.size > 1 || prices.size > 1) {
      conflicting++;
      if (conflicts.length < 15) {
        conflicts.push(
          `    ${barcode}: ` + list.map(d =>
            `${d.data.name || '(unnamed)'} [cost=${d.data.cost_per_bottle ?? '-'} price=${d.data.pour_price ?? '-'}]`
          ).join('  |  ')
        );
      }
    }
  }
  console.log(`  of those, with conflicting data: ${conflicting}`);
  if (conflicts.length) {
    console.log('\n  Conflicting duplicates (review these):');
    conflicts.forEach(c => console.log(c));
    if (conflicting > conflicts.length) console.log(`    … and ${conflicting - conflicts.length} more`);
  }

  // Reference counts, so the impact is visible before deleting anything.
  console.log('\n─── References to duplicate documents ────');
  const loserIds = new Set<string>();
  const winners = new Map<string, Doc>();
  for (const [barcode, list] of dupes) {
    const sorted = [...list].sort((a, b) => score(b) - score(a) || a.id.localeCompare(b.id));
    winners.set(barcode, sorted[0]);
    sorted.slice(1).forEach(d => loserIds.add(d.id));
  }

  const refCounts: Record<string, number> = {};
  for (const ref of REFERENCES) {
    if (ref.collection === 'consumption_reports') continue; // nested, reported separately
    try {
      const snap = await db.collection(ref.collection).get();
      const hits = snap.docs.filter(d => loserIds.has(String(d.data()[ref.field] || '')));
      refCounts[ref.collection] = hits.length;
      console.log(`  ${ref.collection}.${ref.field}: ${hits.length} pointing at a duplicate`);
    } catch (e) {
      console.log(`  ${ref.collection}: could not read (${e.message})`);
    }
  }

  if (!merge) {
    console.log('\nRun with --merge to collapse duplicates and repoint these references.');
    console.log('Take a Firestore export first — the merge deletes documents.');
    return;
  }

  if (!skipConfirm) {
    console.log(`\nAbout to delete ${loserIds.size} documents and repoint their references.`);
    console.log('Press Ctrl-C within 10 seconds to abort…');
    await new Promise(r => setTimeout(r, 10000));
  }

  // 1. Update winners with anything only the losers had.
  console.log('\nMerging field values into canonical documents…');
  let updated = 0;
  const updateOps: { ref: any; data: any }[] = [];
  for (const [barcode, list] of dupes) {
    const winner = winners.get(barcode)!;
    const losers = list.filter(d => d.id !== winner.id).map(d => d.data);
    const merged = mergeInto(winner.data, losers);
    const changed = Object.keys(merged).some(k => merged[k] !== winner.data[k]);
    if (changed) {
      updateOps.push({ ref: db.collection(COLLECTION).doc(winner.id), data: merged });
      updated++;
    }
  }
  for (let i = 0; i < updateOps.length; i += 400) {
    const batch = db.batch();
    updateOps.slice(i, i + 400).forEach(op => batch.set(op.ref, op.data, { merge: true }));
    await batch.commit();
  }
  console.log(`  ${updated} canonical documents enriched from duplicates`);

  // 2. Repoint references from losers to winners.
  const loserToWinner = new Map<string, string>();
  for (const [barcode, list] of dupes) {
    const winner = winners.get(barcode)!;
    list.filter(d => d.id !== winner.id).forEach(d => loserToWinner.set(d.id, winner.id));
  }

  console.log('Repointing references…');
  for (const ref of REFERENCES) {
    if (ref.collection === 'consumption_reports') continue;
    try {
      const snap = await db.collection(ref.collection).get();
      const ops = snap.docs
        .filter(d => loserToWinner.has(String(d.data()[ref.field] || '')))
        .map(d => ({ ref: d.ref, value: loserToWinner.get(String(d.data()[ref.field]))! }));
      for (let i = 0; i < ops.length; i += 400) {
        const batch = db.batch();
        ops.slice(i, i + 400).forEach(op => batch.update(op.ref, { [ref.field]: op.value }));
        await batch.commit();
      }
      if (ops.length) console.log(`  ${ref.collection}: repointed ${ops.length}`);
    } catch (e) {
      console.log(`  ${ref.collection}: FAILED (${e.message})`);
    }
  }

  // 3. Delete the redundant documents.
  console.log('Deleting redundant documents…');
  const ids = Array.from(loserIds);
  for (let i = 0; i < ids.length; i += 400) {
    const batch = db.batch();
    ids.slice(i, i + 400).forEach(id => batch.delete(db.collection(COLLECTION).doc(id)));
    await batch.commit();
    console.log(`  deleted ${Math.min(i + 400, ids.length)}/${ids.length}`);
  }

  console.log('\n─── Done ─────────────────────────────────');
  console.log(`  catalog is now ${snapshot.size - ids.length} documents`);
  console.log(`  every barcode resolves to exactly one product`);
  console.log('\nNote: consumption_reports embed product_ids in their `items` array.');
  console.log('Historical reports are point-in-time snapshots and are left untouched.');
}

if (require.main === module) {
  main()
    .then(() => process.exit(0))
    .catch(err => {
      const detail = `${err?.details || ''} ${err?.message || ''}`;
      if (detail.includes('invalid_rapt') || detail.includes('invalid_grant') || detail.includes('reauth')) {
        console.error('\nGoogle Cloud needs re-authentication:\n  gcloud auth application-default login\n');
      } else {
        console.error(err);
      }
      process.exit(1);
    });
}
